// dummy email used to tag unsubscribe/block emails in filter
export const MAIL_MAGIC_FILTER_EMAIL = 'filter@getmailmagic.com';
export const API_MAX_RESULT = 500;

export const storageKeys = {
  MAIL_MAGIC_WHITELIST_FILTER_ID: 'MAIL_MAGIC_WHITELIST_FILTER_ID',
  IS_APP_ENABLED: 'IS_APP_ENABLED',
  WHITELIST_FILTER_ID: 'WHITELIST_FILTER_ID',
  UNSUBSCRIBE_FILTER_ID: 'UNSUBSCRIBE_FILTER_ID',
  NEWSLETTER_EMAILS: 'NEWSLETTER_EMAILS',
  UNSUBSCRIBED_EMAILS: 'UNSUBSCRIBED_EMAILS',
  WHITELISTED_EMAILS: 'WHITELISTED_EMAILS',
} as const;
