export const storageKeys = {
  UNSUBSCRIBED_EMAILS: 'UNSUBSCRIBED_EMAILS',
  NEWSLETTER_EMAILS: 'NEWSLETTER_EMAILS',
  WHITELISTED_EMAILS: 'WHITELISTED_EMAILS',
  IS_APP_ENABLED: 'IS_APP_ENABLED',
};
